config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :articles do
    resources :comments
  end
  root 'articles#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  http_basic_authenticate_with name: 'admin', password: '123456', except: [:index, :show]
  def index
    @articles = Article.all
  end
  def show
    @article = Article.find(params[:id])
  end
	def new 
	@article = Article.new
	end
	def edit
	@article = Article.find(params[:id])
	end
  def create
  @article = Article.new(article_params)
  if @article.save
  redirect_to @article
  else
    render 'new'
  end
  end
  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end
  private
    def article_params
    params.require(:article).permit(:title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    respond_to do |format|
      format.html { redirect_to @article }
      format.js
    end
  end
  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

    <% if @article.errors.any? %>
        <div id="error_explanation">
          <span class="alert radius label">
            <%= pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:
              </span>
           <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <span class="secondary radius label"><li class = 'no-markers'><%= msg %></li></span><br/>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text, rows: 5  %>
    </p>

    <p>
      <%= f.submit :class => 'button small' %>
    </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<table>
 
  <% @articles.each do |article| %>

      <h3><%= link_to article.title, article_path(article) %></h3>
      <h6>Written by <a href="#">Author</a> on August 12, 2012.</h6>
      <div class="row">
        <div class="large-6 columns">
          <%= truncate(article.text, :length => 450, :omission => '...') %><br />
          <ul class="inline-list right">
            <li><%= link_to 'Read more', article_path(article) %></li>
            <li><%= link_to 'Edit', edit_article_path(article) %></li>
            <li><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: 'Are you sure?'}  %></li>
          </ul>
        </div>
        <div class="large-6 columns">
          <img src="http://placehold.it/400x240&text=[someimg]"/>
        </div>
        <hr>
      </div>

  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <h3><%= @article.title %></h3>
</p>

<p align="justify">
  <%= @article.text %>
</p>
<hr>

<h4>Comments</h4>
<div id = 'comments'>
<%= render @article.comments %>
</div>
<h4>Add a comment:</h4>
<%= render 'comments/form' %>
<ul class="inline-list right">
    <li><%= link_to 'Edit', edit_article_path(@article) %></li>
    <li><%= link_to 'Back', articles_path %></li>
</ul>

app/views/comments/_comment.html.erb
<p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  <br />

  <strong>Comment:</strong>
  <%= comment.body %>
</p>
<hr>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build], :remote => true) do |f| %>
    <p>
      <%= f.label :commenter %><br>
      <%= f.text_field :commenter %>
    </p>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit :class => 'button small' %>
    </p>
<% end %>

app/views/comments/create.js.erb
$('#comments').prepend('<%= escape_javascript(render :partial => @comment) %>');
$('#comment_body').val('')

app/views/layouts/_aside.html.erb
<aside class="large-3 columns">
  <h5>Categories</h5>
  <ul class="side-nav">
    <li><a href="#">News</a></li>
    <li><a href="#">Code</a></li>
    <li><a href="#">Design</a></li>
    <li><a href="#">Fun</a></li>
    <li><a href="#">Weasels</a></li>
  </ul>
  <div class="panel">
    <h5>Featured</h5>
    <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow.</p>
    <a href="#">Read More →</a>
  </div>
</aside>

app/views/layouts/_footer.html.erb
<footer class="row">
  <div class="large-12 columns">
    <hr/>
    <div class="row">
      <div class="large-6 columns">
        <p>© Especially from Vintizer</p>
      </div>
      <div class="large-6 columns">
        <ul class="inline-list right">
          <li><a href="#">Link 1</a></li>
          <li><a href="#">Link 2</a></li>
          <li><a href="#">Link 3</a></li>
          <li><a href="#">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="row">
  <div class="large-12 columns">
    <div class="nav-bar right">
      <ul class="button-group">
        <li><%= link_to 'New article', new_article_path, class: 'button' %></li>
        <li><a href="http://www.brightgrove.com/" target="_blank"  class="button">BrightGrove</a></li>
      </ul>
    </div>
    <h1><%= link_to 'Blog', controller: 'articles' %><small> This is my first RoR blog. It's awesome.</small></h1>
    <hr/>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="header">
  <%= render 'layouts/header' %>
</div>

<div class="row">
  <div class="large-9 columns" role="content">
    <%= yield %>
  </div>
  <%= render 'layouts/aside' %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>